all:
	g++ Principal.cpp -lstdc++fs -o vision.bin -I/usr/local/include/opencv4 -L/usr/lib/x86_64-linux-gnu/ -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_video -lopencv_videoio

run:
	./vision.bin